services:
  - type: web
    name: my-backend-service
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    region: oregon
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: your-database-url
      - key: PORT
        value: 3000
